services:

  dev-container:
    image: mcr.microsoft.com/devcontainers/python:3.12-bullseye
    container_name: python-dev-container
    working_dir: /workspace
    ports:
      - "8000:8000"
    command: >
      sh -c "
      pip install --root-user-action=ignore -U pip &&
      tail -f /dev/null"
    volumes:
      - ./workspace:/workspace:cached,uid=1000,gid=1000
    tty: true

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./MinIO/.env
    volumes:
      - ./MinIO/data:/data
      - ./MinIO/config:/root/.minio
    command: server /data --console-address ":9001"

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    env_file:
      - ./mlflow/.env
    volumes:
      - ./mlflow/data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/mlflow_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"