services:

  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./MinIO/.env
    volumes:
      - ./MinIO/data:/data
      - ./MinIO/config:/root/.minio
    command: server /data --console-address ":9001"
    networks:
      - ds-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    container_name: mlflow
    ports:
      - "5000:5000"
    env_file:
      - ./mlflow/.env
    volumes:
      - ./mlflow/data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
    networks:
      - ds-network

  postgres:
    image: postgres:17.2
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/mlflow_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ds-network

networks:
  ds-network:
    driver: bridge